# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_dtm_original_mem_test <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_original_mem_test', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_original <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_original', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel_mem_test <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel_mem_test', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel_Lists_mem_test <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel_Lists_mem_test', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel_Lists <- function(strings_, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel_Lists', PACKAGE = 'tmParallel', strings_, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

mem_test <- function() {
    .Call('tmParallel_mem_test', PACKAGE = 'tmParallel')
}

R_Cpp_transition_test <- function(terms, out_vectors_length) {
    .Call('tmParallel_R_Cpp_transition_test', PACKAGE = 'tmParallel', terms, out_vectors_length)
}

TfIdfParallel <- function(word_, text_, count_, termsCount_, documentCount_, normalizeTf, IdfPlus1) {
    .Call('tmParallel_TfIdfParallel', PACKAGE = 'tmParallel', word_, text_, count_, termsCount_, documentCount_, normalizeTf, IdfPlus1)
}

