# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_dtm_original <- function(strings, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_original', PACKAGE = 'tmParallel', strings, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel_v1 <- function(strings, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel_v1', PACKAGE = 'tmParallel', strings, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

Cpp_dtm_parallel_v2 <- function(strings, min_term_freq, max_term_freq, min_word_length, max_word_length) {
    .Call('tmParallel_Cpp_dtm_parallel_v2', PACKAGE = 'tmParallel', strings, min_term_freq, max_term_freq, min_word_length, max_word_length)
}

